"""Compatibility imports for the shared oracle answer presentation helpers."""

from maxpane_dashboard.widgets.seat_oracle_answer import (
    __all__,
    ORACLE_NODE_KEYS,
    bytes32_text,
    tok_text,
    failed_answer,
    valid_identity,
    joined,
    seat_value,
    consensus_value,
    panel_text,
    can_open_submission,
    record_answer,
    fit_popup_text,
    _STATE_COLORS,
    _PANEL_COLS,
    _HASH,
    _BYTES32,
    _count,
    re,
    Style,
    Text,
    rowfit,
    is_job_id,
    for_chain_id,
    sanitize_cell,
    strip_tags,
    DASH,
    EMDASH,
    fmt_compact,
    mark_addresses,
    keep_units,
    link_prose,
    unmark,
)
