"""``SeriesCache`` -- the one copy of the six caches' persistence code.

Five cache modules used to carry their own atomic write, their own
open/decode guard, their own per-point validation and their own
"Skipped ..." warning.  Branch 9 folded them into
``data/series_cache.SeriesCache``; these tests drive the base directly
through a probe subclass, and then drive the two real subclasses this
work package migrated against **fixtures written by the pre-branch
commit** (``tests/fixtures/cache/*_53a71d5.json``, generated by
``tests/scripts/make_cache_fixtures.py`` from a worktree of ``53a71d5``).
The fixture round-trips are the acceptance claim: a user's existing
``~/.maxpane/cattown_cache.json`` loads into the new class with exactly
the points the old class wrote.  WP-B appended the bakery and Base
token caches at the bottom of this file.

The expected point lists below are transcribed from those files by hand.
Recomputing them from the same constants the fixture was built with
would prove only that arithmetic is deterministic.

Nothing here touches the network, the real clipboard or ``~/.maxpane``:
every path is ``tmp_path`` or a committed fixture, and every clock is
passed in.
"""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path

import pytest

from maxpane_dashboard.data.base_cache import BaseTokenCache
from maxpane_dashboard.data.base_models import BaseToken
from maxpane_dashboard.data.cache import DataCache
from maxpane_dashboard.data.cattown_cache import CatTownCache
from maxpane_dashboard.data.dota_cache import DOTACache
from maxpane_dashboard.data.dota_models import (
    DOTABase,
    DOTAGameState,
    DOTALane,
    DOTASnapshot,
)
from maxpane_dashboard.data.series_cache import SeriesCache, SeriesSpec

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "cache"

# The clock the fixtures were written against; every sample in them is at
# or before it, so no test here leans on the clock-skew tolerance.
FIXTURE_NOW = 1_758_000_000.0

DAY = 86_400.0


class _Snapshot:
    """The one attribute ``_mark`` reads off a snapshot."""

    def __init__(self, fetched_at: float) -> None:
        self.fetched_at = fetched_at


class _Probe(SeriesCache):
    """Two series that exercise the two per-spec knobs.

    ``deltas`` names its own ``maxlen`` and allows negatives (a delta
    series legitimately goes below zero); ``counts`` takes the cache-wide
    ``max_history`` and its own ``max_age`` window.
    """

    SERIES = (
        SeriesSpec("counts", max_age=600.0),
        SeriesSpec("deltas", maxlen=3, allow_negative=True),
    )
    NOUN = "Probe cache"


# ---------------------------------------------------------------------------
# record(): the sentinel rule
# ---------------------------------------------------------------------------


def test_record_drops_none_and_says_so() -> None:
    """CLAUDE.md: a failed read is ``None``, never ``0``.

    The series is persisted, so a sentinel written during an outage
    outlives it and reads afterwards as a real measurement.
    """
    cache = _Probe()

    assert cache.record("counts", 100.0, None) is False

    assert cache.get_series("counts") == []
    assert len(cache.counts) == 0


def test_record_keeps_a_real_zero() -> None:
    """The other half of the rule: ``0.0`` is a value, not a sentinel."""
    cache = _Probe()

    assert cache.record("counts", 100.0, 0.0) is True

    assert cache.get_series("counts") == [(100.0, 0.0)]


def test_record_coerces_to_float_and_respects_the_per_spec_maxlen() -> None:
    cache = _Probe(max_history=120)

    for i in range(5):
        cache.record("deltas", 100.0 + i, i)

    # maxlen=3 on the spec beats max_history=120.
    assert cache.get_series("deltas") == [(102.0, 2.0), (103.0, 3.0), (104.0, 4.0)]
    assert all(isinstance(v, float) for _, v in cache.get_series("deltas"))


def test_history_size_counts_the_first_declared_series() -> None:
    cache = _Probe()
    cache.record("deltas", 100.0, 1.0)
    assert cache.history_size == 0

    cache.record("counts", 100.0, 1.0)
    assert cache.history_size == 1


def test_mark_sets_latest_and_last_updated() -> None:
    cache = _Probe()
    assert cache.get_latest() is None
    assert cache.last_updated is None

    snap = _Snapshot(1_700_000_000.0)
    cache._mark(snap)

    assert cache.get_latest() is snap
    assert cache.last_updated == 1_700_000_000.0


# ---------------------------------------------------------------------------
# load_from_file(): the injected clock
# ---------------------------------------------------------------------------


def _write(path: Path, payload) -> str:
    path.write_text(json.dumps(payload))
    return str(path)


def test_load_validates_points_against_now_not_the_wall_clock(tmp_path) -> None:
    """``now=`` is the reference, or the same file loads differently by hour.

    The good point is 400 s *after* the injected ``now`` -- beyond the
    300 s skew tolerance, so it is corruption from that clock's point of
    view. Against the real wall clock (2026 and counting) it is deep in
    the past and would survive, so a loader that reached for
    ``time.time()`` here would keep it.
    """
    base = 1_700_000_000.0
    path = _write(
        tmp_path / "probe.json",
        {"counts": [[base - 60, 1.0], [base + 400, 2.0]]},
    )
    cache = _Probe()

    cache.load_from_file(path, now=base)

    assert cache.get_series("counts") == [(base - 60, 1.0)]


def test_a_spec_max_age_beats_the_calls_max_age(tmp_path) -> None:
    """``counts`` windows itself at 600 s; ``deltas`` takes the argument."""
    base = 1_700_000_000.0
    path = _write(
        tmp_path / "probe.json",
        {
            "counts": [[base - 900, 1.0], [base - 300, 2.0]],
            "deltas": [[base - 900, 3.0], [base - 300, 4.0]],
        },
    )
    cache = _Probe()

    # A generous call-level window: the spec's 600 s still drops the
    # 900-s-old count, while the un-specced deltas keep both points.
    cache.load_from_file(path, now=base, max_age=10 * DAY)

    assert cache.get_series("counts") == [(base - 300, 2.0)]
    assert cache.get_series("deltas") == [(base - 900, 3.0), (base - 300, 4.0)]


def test_allow_negative_is_per_spec(tmp_path) -> None:
    base = 1_700_000_000.0
    path = _write(
        tmp_path / "probe.json",
        {"counts": [[base - 10, -1.0]], "deltas": [[base - 10, -1.0]]},
    )
    cache = _Probe()

    cache.load_from_file(path, now=base)

    assert cache.get_series("counts") == []
    assert cache.get_series("deltas") == [(base - 10.0, -1.0)]


# ---------------------------------------------------------------------------
# load_from_file(): hostile payloads
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("payload", [[], "x", None, 7], ids=["list", "str", "null", "int"])
def test_a_non_dict_payload_leaves_the_cache_untouched(
    tmp_path, caplog, payload
) -> None:
    """A top-level JSON list used to raise ``AttributeError`` out of two
    loaders. Every manager loads its cache in ``__init__``, so that took
    down every dashboard, not just the one owning the file."""
    path = _write(tmp_path / "probe.json", payload)
    cache = _Probe()
    cache.record("counts", 1_700_000_000.0, 42.0)

    with caplog.at_level("WARNING"):
        cache.load_from_file(path, now=1_700_000_000.0)  # must not raise

    assert cache.get_series("counts") == [(1_700_000_000.0, 42.0)]
    assert "unexpected format" in caplog.text


def test_a_missing_file_is_not_an_error(tmp_path, caplog) -> None:
    cache = _Probe()
    with caplog.at_level("INFO"):
        cache.load_from_file(str(tmp_path / "nope.json"), now=1.0)
    assert cache.get_series("counts") == []
    assert "No Probe cache file to load" in caplog.text


def test_the_skipped_warning_names_the_count_and_the_cache(tmp_path, caplog) -> None:
    """The word ``Skipped`` is asserted by ``test_cache_corruption.py``."""
    base = 1_700_000_000.0
    path = _write(
        tmp_path / "probe.json", {"counts": [[base - 10, None], [base - 5, 1.0]]}
    )
    cache = _Probe()

    with caplog.at_level("WARNING"):
        cache.load_from_file(path, now=base)

    assert cache.get_series("counts") == [(base - 5, 1.0)]
    assert "Skipped 1 unusable or expired point(s)" in caplog.text
    assert "Probe cache" in caplog.text


def test_load_clears_before_extending(tmp_path) -> None:
    """R7. A load after an update is a restore, not a concatenation."""
    base = 1_700_000_000.0
    path = _write(tmp_path / "probe.json", {"counts": [[base - 20, 7.0]]})
    cache = _Probe()
    cache.record("counts", base - 10, 99.0)

    cache.load_from_file(path, now=base)

    assert cache.get_series("counts") == [(base - 20, 7.0)]


# ---------------------------------------------------------------------------
# Version key
# ---------------------------------------------------------------------------


class _Versioned(_Probe):
    VERSION_KEY = "schema_version"
    VERSION = 2

    def __init__(self, max_history: int = 120) -> None:
        super().__init__(max_history)
        self.seen_versions: list[int] = []

    def before_load(self, payload, version) -> None:
        self.seen_versions.append(version)


@pytest.mark.parametrize(
    ("stored", "expected"),
    [(2, 2), ("banana", 1), (None, 1), (0, 1)],
    ids=["v2", "non-int", "null", "zero"],
)
def test_before_load_sees_the_version(tmp_path, stored, expected) -> None:
    path = _write(tmp_path / "probe.json", {"schema_version": stored, "counts": []})
    cache = _Versioned()

    cache.load_from_file(path, now=1_700_000_000.0)

    assert cache.seen_versions == [expected]


def test_a_cache_with_no_version_key_reads_version_1(tmp_path) -> None:
    """And writes no version key: adding one to a file that never had one
    makes an older build read its own file as a downgrade."""

    class _Unversioned(_Versioned):
        VERSION_KEY = None

    path = _write(tmp_path / "probe.json", {"schema_version": 2, "counts": []})
    cache = _Unversioned()

    cache.load_from_file(path, now=1_700_000_000.0)
    assert cache.seen_versions == [1]

    out = tmp_path / "out.json"
    cache.save_to_file(str(out))
    # The whole key set, not just the absence of one name: a mutation
    # that writes the version under the base's own default key would
    # sail past ``"schema_version" not in ...``.
    assert set(json.loads(out.read_text())) == {
        "saved_at",
        "max_history",
        "counts",
        "deltas",
    }


def test_a_version_key_is_written_when_the_subclass_names_one(tmp_path) -> None:
    out = tmp_path / "out.json"
    _Versioned().save_to_file(str(out))
    assert json.loads(out.read_text())["schema_version"] == 2


# ---------------------------------------------------------------------------
# save_to_file(): the atomic write
# ---------------------------------------------------------------------------


def test_a_failed_write_leaves_no_tmp_file_behind(tmp_path, caplog) -> None:
    """``os.replace`` failing must not leave ``<path>.tmp`` to accumulate."""
    target = tmp_path / "probe.json"
    cache = _Probe()
    cache.record("counts", 1.0, 1.0)

    real_replace = os.replace

    def _boom(src, dst):
        raise OSError("disk full")

    os.replace = _boom
    try:
        with caplog.at_level("WARNING"):
            cache.save_to_file(str(target))  # must not raise
    finally:
        os.replace = real_replace

    assert not (tmp_path / "probe.json.tmp").exists()
    assert not target.exists()
    assert "Failed to save Probe cache" in caplog.text


def test_a_read_only_directory_is_not_fatal(tmp_path, caplog) -> None:
    """The other half of the same guard, without patching anything."""
    ro = tmp_path / "ro"
    ro.mkdir()
    target = ro / "probe.json"
    os.chmod(ro, stat.S_IRUSR | stat.S_IXUSR)
    try:
        with caplog.at_level("WARNING"):
            _Probe().save_to_file(str(target))  # must not raise
        assert list(ro.iterdir()) == []
    finally:
        os.chmod(ro, stat.S_IRWXU)

    assert "Failed to save Probe cache" in caplog.text


def test_save_then_load_round_trips_the_series(tmp_path) -> None:
    base = 1_700_000_000.0
    cache = _Probe()
    for i in range(4):
        cache.record("counts", base - 100 + i, i * 1.5)
        cache.record("deltas", base - 100 + i, -i)
    before = (cache.get_series("counts"), cache.get_series("deltas"))

    path = tmp_path / "probe.json"
    cache.save_to_file(str(path))
    reloaded = _Probe()
    reloaded.load_from_file(str(path), now=base)

    assert (reloaded.get_series("counts"), reloaded.get_series("deltas")) == before


def test_the_payload_carries_saved_at_and_max_history(tmp_path) -> None:
    path = tmp_path / "probe.json"
    _Probe(max_history=42).save_to_file(str(path))
    payload = json.loads(path.read_text())

    assert payload["max_history"] == 42
    assert isinstance(payload["saved_at"], float)
    assert set(payload) == {"saved_at", "max_history", "counts", "deltas"}


# ---------------------------------------------------------------------------
# The hooks the later work packages need
# ---------------------------------------------------------------------------


def test_extra_payload_and_restore_extra_round_trip(tmp_path) -> None:
    class _WithExtra(_Probe):
        def __init__(self, max_history: int = 120) -> None:
            super().__init__(max_history)
            self.holder_count: int | None = None

        def extra_payload(self):
            return {"holder_count": self.holder_count}

        def restore_extra(self, payload, *, path, now, max_age=None):
            self.holder_count = payload.get("holder_count")
            return 3  # pretend three keyed points were unusable

    path = tmp_path / "probe.json"
    cache = _WithExtra()
    cache.holder_count = 17
    cache.save_to_file(str(path))
    assert json.loads(path.read_text())["holder_count"] == 17

    reloaded = _WithExtra()
    reloaded.load_from_file(str(path), now=1_700_000_000.0)
    assert reloaded.holder_count == 17


def test_restore_extras_dropped_count_reaches_the_skipped_warning(
    tmp_path, caplog
) -> None:
    class _DroppingExtra(_Probe):
        def restore_extra(self, payload, *, path, now, max_age=None):
            return 5

    path = _write(tmp_path / "probe.json", {"counts": []})
    with caplog.at_level("WARNING"):
        _DroppingExtra().load_from_file(path, now=1.0)

    assert "Skipped 5 unusable or expired point(s)" in caplog.text


def test_coerce_keyed_validates_each_key(tmp_path) -> None:
    base = 1_700_000_000.0
    raw = {
        "0xaaa": [[base - 10, 1.0], [base - 5, None]],
        "0xbbb": "not a series",
        "0xccc": [[base - 10, -1.0]],
    }

    series, dropped = _Probe().coerce_keyed(raw, now=base)

    assert series == {"0xaaa": [(base - 10, 1.0)], "0xccc": []}
    assert dropped == 2


def test_coerce_keyed_tolerates_a_non_dict() -> None:
    assert _Probe().coerce_keyed(["nope"], now=1.0) == ({}, 0)


# ---------------------------------------------------------------------------
# CatTownCache -- fixture round-trip against the pre-branch file
# ---------------------------------------------------------------------------

# Transcribed by hand from tests/fixtures/cache/cattown_53a71d5.json.
CATTOWN_PRIZE_POOL = [
    (1757999850.0, 1000.0),
    (1757999880.0, 1010.0),
    (1757999910.0, 1020.0),
    (1757999940.0, 1030.0),
    (1757999970.0, 1040.0),
    (1758000000.0, 1050.0),
]
CATTOWN_LEADER_WEIGHT = [
    (1757999850.0, 3.5),
    (1757999880.0, 3.75),
    (1757999910.0, 4.0),
    (1757999940.0, 4.25),
    (1757999970.0, 4.5),
    (1758000000.0, 4.75),
]
CATTOWN_RAFFLE_TICKETS = [
    (1757999850.0, 100.0),
    (1757999880.0, 105.0),
    (1757999910.0, 110.0),
    (1757999940.0, 115.0),
    (1757999970.0, 120.0),
    (1758000000.0, 125.0),
]

# Transcribed by hand from tests/fixtures/cache/dota_53a71d5.json.
DOTA_TOP = [
    (1757999850.0, 10.0),
    (1757999880.0, 11.0),
    (1757999910.0, 12.0),
    (1757999940.0, 13.0),
    (1757999970.0, 14.0),
    (1758000000.0, 15.0),
]
DOTA_MID = [
    (1757999850.0, 20.0),
    (1757999880.0, 22.0),
    (1757999910.0, 24.0),
    (1757999940.0, 26.0),
    (1757999970.0, 28.0),
    (1758000000.0, 30.0),
]
DOTA_BOT = [
    (1757999850.0, 30.0),
    (1757999880.0, 33.0),
    (1757999910.0, 36.0),
    (1757999940.0, 39.0),
    (1757999970.0, 42.0),
    (1758000000.0, 45.0),
]


def test_cattown_loads_a_pre_branch_cache_file() -> None:
    """A user's ``~/.maxpane/cattown_cache.json`` written by ``53a71d5``."""
    cache = CatTownCache(max_history=120)

    cache.load_from_file(str(FIXTURES / "cattown_53a71d5.json"), now=FIXTURE_NOW)

    assert cache.get_prize_pool_history() == CATTOWN_PRIZE_POOL
    assert cache.get_leader_weight_history() == CATTOWN_LEADER_WEIGHT
    assert cache.get_raffle_tickets_history() == CATTOWN_RAFFLE_TICKETS
    assert cache.history_size == 6


def test_dota_loads_a_pre_branch_cache_file() -> None:
    cache = DOTACache(max_history=120)

    cache.load_from_file(str(FIXTURES / "dota_53a71d5.json"), now=FIXTURE_NOW)

    assert cache.get_top_history() == DOTA_TOP
    assert cache.get_mid_history() == DOTA_MID
    assert cache.get_bot_history() == DOTA_BOT
    assert cache.history_size == 6


@pytest.mark.parametrize(
    ("name", "cls"),
    [("cattown", CatTownCache), ("dota", DOTACache)],
)
def test_the_persisted_shape_did_not_change(tmp_path, name, cls) -> None:
    """Load the pre-branch file, save it again, compare key for key.

    ``saved_at`` is the wall clock at write time and is the only key
    allowed to differ.  Notably, neither file gains a version key.
    """
    old = json.loads((FIXTURES / f"{name}_53a71d5.json").read_text())
    cache = cls(max_history=120)
    cache.load_from_file(str(FIXTURES / f"{name}_53a71d5.json"), now=FIXTURE_NOW)

    out = tmp_path / f"{name}.json"
    cache.save_to_file(str(out))
    new = json.loads(out.read_text())

    assert set(new) == set(old)
    assert "version" not in new and "schema_version" not in new
    for key in old:
        if key == "saved_at":
            continue
        assert new[key] == old[key], key


# ---------------------------------------------------------------------------
# R4: the unwindowed caches stay unwindowed on this branch
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("cls", "key", "getter"),
    [
        (CatTownCache, "prize_pool_history", "get_prize_pool_history"),
        (DOTACache, "top_history", "get_top_history"),
    ],
)
def test_a_thirty_day_old_point_still_loads(tmp_path, cls, key, getter) -> None:
    """These two caches never windowed their restored points and this
    branch does not start: narrowing the window would silently shorten
    users' histories (follow-up #42 decides whether to)."""
    now = 1_700_000_000.0
    old_ts = now - 30 * DAY
    path = _write(tmp_path / "cache.json", {key: [[old_ts, 5.0]]})

    cache = cls(max_history=120)
    cache.load_from_file(path, now=now)

    assert getattr(cache, getter)() == [(old_ts, 5.0)]


# ---------------------------------------------------------------------------
# DOTACache.update -- the lane guard
# ---------------------------------------------------------------------------


def _dota_state(lanes: dict[str, DOTALane]) -> DOTAGameState:
    base = DOTABase(hp=1_000, maxHp=1_000)
    return DOTAGameState(
        tick=1,
        agents={},
        lanes=lanes,
        towers=[],
        bases={"human": base, "orc": base},
        heroes=[],
        winner=None,
    )


def test_a_missing_lane_records_nothing() -> None:
    """A frontline of 0 is a level lane, so an absent lane must not
    become one: it would draw a battle that never happened."""
    cache = DOTACache()
    lanes = {"top": DOTALane(human=5, orc=5, frontline=7)}

    cache.update(DOTASnapshot(fetched_at=1_700_000_000.0, game_state=_dota_state(lanes)))

    assert cache.get_top_history() == [(1_700_000_000.0, 7.0)]
    assert cache.get_mid_history() == []
    assert cache.get_bot_history() == []


def test_a_game_state_that_could_not_be_read_records_nothing() -> None:
    cache = DOTACache()

    cache.update(DOTASnapshot(fetched_at=1_700_000_000.0, game_state=None))

    assert cache.get_top_history() == []
    assert cache.get_mid_history() == []
    assert cache.get_bot_history() == []
    assert cache.last_updated == 1_700_000_000.0


def test_a_zero_frontline_is_recorded() -> None:
    """The real negative stays representable: the lane really is level."""
    cache = DOTACache()
    lanes = {
        "top": DOTALane(human=5, orc=5, frontline=0),
        "mid": DOTALane(human=5, orc=5, frontline=0),
        "bot": DOTALane(human=5, orc=5, frontline=0),
    }

    cache.update(DOTASnapshot(fetched_at=1_700_000_000.0, game_state=_dota_state(lanes)))

    assert cache.get_top_history() == [(1_700_000_000.0, 0.0)]


# ===========================================================================
# WP-B: the bakery cache (``DataCache``) and the Base token cache
# ===========================================================================
#
# Both are dict-of-series caches: no fixed series for bakery, three fixed
# overview series plus a keyed dict for base.  Both gained the
# ``isinstance(payload, dict)`` guard they never had (R5), and base's
# overview deques now clear before extending (R7).

# Transcribed by hand from tests/fixtures/cache/history_53a71d5.json.
BAKERY_HISTORIES = {
    "Sourdough Syndicate": [
        (1757999850.0, 100.0),
        (1757999880.0, 101.0),
        (1757999910.0, 102.0),
        (1757999940.0, 103.0),
        (1757999970.0, 104.0),
        (1758000000.0, 105.0),
    ],
    "Rye Republic": [
        (1757999850.0, 50.0),
        (1757999880.0, 52.0),
        (1757999910.0, 54.0),
        (1757999940.0, 56.0),
        (1757999970.0, 58.0),
        (1758000000.0, 60.0),
    ],
    "Crumb Cartel": [
        (1757999850.0, 25.0),
        (1757999880.0, 28.0),
        (1757999910.0, 31.0),
        (1757999940.0, 34.0),
        (1757999970.0, 37.0),
        (1758000000.0, 40.0),
    ],
}

# Transcribed by hand from tests/fixtures/cache/base_53a71d5.json.
BASE_TOKEN_1 = "0x0000000000000000000000000000000000000001"
BASE_TOKEN_2 = "0x0000000000000000000000000000000000000002"
BASE_TOKEN_3 = "0x0000000000000000000000000000000000000003"
BASE_HISTORIES = {
    BASE_TOKEN_1: [
        (1757999850.0, 1.0),
        (1757999880.0, 1.1),
        (1757999910.0, 1.2),
        (1757999940.0, 1.3),
        (1757999970.0, 1.4),
        (1758000000.0, 1.5),
    ],
    BASE_TOKEN_2: [
        (1757999850.0, 20.0),
        (1757999880.0, 20.5),
        (1757999910.0, 21.0),
        (1757999940.0, 21.5),
        (1757999970.0, 22.0),
        (1758000000.0, 22.5),
    ],
    BASE_TOKEN_3: [
        (1757999850.0, 300.0),
        (1757999880.0, 302.0),
        (1757999910.0, 304.0),
        (1757999940.0, 306.0),
        (1757999970.0, 308.0),
        (1758000000.0, 310.0),
    ],
}
BASE_VOLUME = [
    (1757999850.0, 1000000.0),
    (1757999880.0, 1010000.0),
    (1757999910.0, 1020000.0),
    (1757999940.0, 1030000.0),
    (1757999970.0, 1040000.0),
    (1758000000.0, 1050000.0),
]
BASE_ETH_PRICE = [
    (1757999850.0, 2500.0),
    (1757999880.0, 2505.0),
    (1757999910.0, 2510.0),
    (1757999940.0, 2515.0),
    (1757999970.0, 2520.0),
    (1758000000.0, 2525.0),
]
BASE_TRADE_COUNT = [
    (1757999850.0, 40000.0),
    (1757999880.0, 40100.0),
    (1757999910.0, 40200.0),
    (1757999940.0, 40300.0),
    (1757999970.0, 40400.0),
    (1758000000.0, 40500.0),
]


def _base_token(address: str, price: float) -> BaseToken:
    """The two fields ``record_token`` reads off a token."""
    return BaseToken(
        address=address,
        name="Token",
        symbol="TKN",
        price_usd=price,
        price_change_5m=None,
        price_change_1h=None,
        price_change_24h=None,
        volume_24h=0.0,
        market_cap=0.0,
        fdv=None,
        liquidity=0.0,
        pair_address=None,
        dex=None,
        created_at=None,
    )


# ---------------------------------------------------------------------------
# Fixture round-trips against the pre-branch files
# ---------------------------------------------------------------------------


def test_bakery_loads_a_pre_branch_cache_file() -> None:
    """A user's ``~/.maxpane/history_cache.json`` written by ``53a71d5``."""
    cache = DataCache(max_history=120)

    cache.load_from_file(str(FIXTURES / "history_53a71d5.json"), now=FIXTURE_NOW)

    assert cache.get_all_histories() == BAKERY_HISTORIES
    assert cache.get_cookie_history("Rye Republic") == BAKERY_HISTORIES["Rye Republic"]
    assert cache.get_cookie_history("No Such Bakery") == []
    # history_size is the bakery count, not a point count (R6).
    assert cache.history_size == 3


def test_base_loads_a_pre_branch_cache_file() -> None:
    """A user's ``~/.maxpane/base_cache.json`` written by ``53a71d5``.

    Both halves of that file: the keyed token histories *and* the three
    overview series, which are persisted under ``overview_*`` names while
    the attributes are ``*_history`` -- the reason ``SeriesSpec`` grew a
    ``key``.
    """
    cache = BaseTokenCache(max_history=120)

    cache.load_from_file(str(FIXTURES / "base_53a71d5.json"), now=FIXTURE_NOW)

    assert cache.get_all_histories() == BASE_HISTORIES
    assert cache.get_price_history(BASE_TOKEN_2) == BASE_HISTORIES[BASE_TOKEN_2]
    assert cache.get_volume_history() == BASE_VOLUME
    assert cache.get_eth_price_history() == BASE_ETH_PRICE
    assert cache.get_trade_count_history() == BASE_TRADE_COUNT
    assert cache.history_size == 3


@pytest.mark.parametrize(
    ("name", "cls"),
    [("history", DataCache), ("base", BaseTokenCache)],
    ids=["bakery", "base"],
)
def test_wp_b_resaves_the_pre_branch_file_key_for_key(tmp_path, name, cls) -> None:
    """Load the pre-branch file, save it again, compare *including order*.

    ``saved_at`` is the wall clock at write time and is the only key
    allowed to differ.  Key order is asserted because a save that
    reshuffles a user's file makes every backup diff unreadable, and
    because the order is the one thing a set comparison cannot see.
    Neither file gains a version key.
    """
    fixture = FIXTURES / f"{name}_53a71d5.json"
    old = json.loads(fixture.read_text())
    cache = cls(max_history=120)
    cache.load_from_file(str(fixture), now=FIXTURE_NOW)

    out = tmp_path / f"{name}.json"
    cache.save_to_file(str(out))
    new = json.loads(out.read_text())

    assert list(new) == list(old)
    assert "version" not in new and "schema_version" not in new
    del old["saved_at"], new["saved_at"]
    assert new == old


# ---------------------------------------------------------------------------
# R5: a top-level JSON list reaches every real loader without raising
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "cls",
    [DataCache, BaseTokenCache, CatTownCache, DOTACache],
    ids=["bakery", "base", "cattown", "dota"],
)
def test_an_empty_list_payload_leaves_a_real_cache_untouched(
    tmp_path, caplog, cls
) -> None:
    """R5, on the four migrated classes rather than on the probe.

    ``cache.py`` and ``base_cache.py`` went straight to ``payload.get``,
    so a top-level JSON list raised ``AttributeError`` out of the loader
    -- and every manager loads its cache in ``__init__``, so one
    hand-edited file took down every dashboard.
    """
    path = _write(tmp_path / "cache.json", [])
    cache = cls(max_history=120)

    with caplog.at_level("WARNING"):
        cache.load_from_file(path, now=FIXTURE_NOW)  # must not raise

    assert cache.history_size == 0
    assert cache.get_latest() is None
    assert "unexpected format" in caplog.text


# ---------------------------------------------------------------------------
# R7: base clears its overview deques before extending
# ---------------------------------------------------------------------------


def test_base_overview_load_replaces_rather_than_concatenates(tmp_path) -> None:
    """A load after an update is a restore, not an append.

    ``base_cache.py`` used to ``extend`` the three overview deques with
    no ``clear()``, so a reload mid-session left this process's own
    samples in front of the file's -- two disjoint runs welded into one
    sparkline, with a gap the trend maths reads as a move.
    """
    base = 1_700_000_000.0
    path = _write(
        tmp_path / "base_cache.json",
        {
            "overview_volume": [[base - 60, 10.0]],
            "overview_eth_price": [[base - 60, 2000.0]],
            "overview_trade_count": [[base - 60, 5.0]],
        },
    )
    cache = BaseTokenCache(max_history=120)
    cache.record_overview_point(
        timestamp=base - 10, total_volume=999.0, eth_price=3000.0, trade_count=7
    )

    cache.load_from_file(path, now=base)

    assert cache.get_volume_history() == [(base - 60, 10.0)]
    assert cache.get_eth_price_history() == [(base - 60, 2000.0)]
    assert cache.get_trade_count_history() == [(base - 60, 5.0)]


# ---------------------------------------------------------------------------
# R1/R3: the two rules about what a timestamp and a value may be
# ---------------------------------------------------------------------------


def test_record_token_honours_a_zero_timestamp() -> None:
    """R3. ``ts = timestamp or time.time()`` swallowed epoch ``0.0``.

    ``0.0`` is falsy, so the one caller who meant "stamp this at the
    epoch" silently got the wall clock instead -- the single value a
    test can use to tell an injected clock from a real one.  The
    in-memory point is what is asserted: ``coerce_points`` rejects a
    non-positive timestamp as corruption, so a ``0.0`` point does not
    survive a save/load round trip, and that is deliberate.
    """
    cache = BaseTokenCache(max_history=10)

    cache.record_token(_base_token(BASE_TOKEN_1, 4.5), timestamp=0.0)

    assert cache.get_price_history(BASE_TOKEN_1) == [(0.0, 4.5)]


def test_record_overview_point_skips_none_and_keeps_a_real_zero() -> None:
    """R1, on the method that is the repo's reference statement of it.

    A zero written while the upstream was down is persisted and then
    indistinguishable from a real reading: it crushes the ETH
    sparkline's scale and ``compute_volume_trend`` reads a zero previous
    volume as "Rising" on the next good cycle whatever the truth is.
    """
    cache = BaseTokenCache(max_history=10)

    cache.record_overview_point(
        timestamp=100.0, total_volume=None, eth_price=None, trade_count=None
    )
    cache.record_overview_point(
        timestamp=200.0, total_volume=0.0, eth_price=2500.0, trade_count=0
    )

    assert cache.get_volume_history() == [(200.0, 0.0)]
    assert cache.get_eth_price_history() == [(200.0, 2500.0)]
    assert cache.get_trade_count_history() == [(200.0, 0.0)]


# ---------------------------------------------------------------------------
# R4: base stays unwindowed; bakery keeps its caller-supplied window
# ---------------------------------------------------------------------------


def test_base_restores_a_thirty_day_old_point(tmp_path) -> None:
    """Base has never windowed a restored point and this branch does not
    start: narrowing the window would silently shorten users' histories
    (follow-up #42 decides whether to)."""
    now = 1_700_000_000.0
    old_ts = now - 30 * DAY
    path = _write(
        tmp_path / "base_cache.json",
        {
            "histories": {BASE_TOKEN_1: [[old_ts, 3.0]]},
            "overview_volume": [[old_ts, 7.0]],
        },
    )
    cache = BaseTokenCache(max_history=120)

    cache.load_from_file(path, now=now)

    assert cache.get_price_history(BASE_TOKEN_1) == [(old_ts, 3.0)]
    assert cache.get_volume_history() == [(old_ts, 7.0)]


def test_bakery_still_drops_points_outside_the_callers_window(tmp_path) -> None:
    """The other half of R4: ``manager.py:67-69`` passes the sparkline
    window, and the hook must still receive it.  ``calculate_production_rate``
    regresses over whatever is in the deque, so a day-old cluster plus a
    fresh one answers with the long-run average (MEDI-22)."""
    now = 1_700_000_000.0
    path = _write(
        tmp_path / "cache.json",
        {"histories": {"Alpha": [[now - 30 * DAY, 1.0], [now - 60, 2.0]]}},
    )
    cache = DataCache(max_history=120)

    cache.load_from_file(path, now=now, max_age=3600.0)

    assert cache.get_cookie_history("Alpha") == [(now - 60, 2.0)]


def test_a_bakery_whose_points_all_expired_is_left_untracked(tmp_path) -> None:
    """Unique to this cache, and kept: an empty deque is a bakery we are
    following with nothing to show, and ``history_size`` counts it."""
    now = 1_700_000_000.0
    path = _write(
        tmp_path / "cache.json",
        {
            "histories": {
                "Ghost": [[now - 30 * DAY, 1.0]],
                "Alive": [[now - 60, 2.0]],
            }
        },
    )
    cache = DataCache(max_history=120)

    cache.load_from_file(path, now=now, max_age=3600.0)

    assert cache.get_cookie_history("Ghost") == []
    assert "Ghost" not in cache.get_all_histories()
    assert cache.history_size == 1


# ---------------------------------------------------------------------------
# M2: a declared series key holding a non-list says so
# ---------------------------------------------------------------------------


def test_a_series_key_that_is_not_a_list_is_named_in_a_warning(
    tmp_path, caplog
) -> None:
    """``coerce_points`` degrades a non-list to "no points", which is
    right and silent: the sparkline empties and nothing says why.  A
    hand-edited cache file is third-party input and the user is the only
    one who can fix it, so the key is named."""
    base = 1_700_000_000.0
    path = _write(
        tmp_path / "base_cache.json",
        {"overview_volume": {"ts": 1}, "overview_eth_price": [[base - 10, 1.0]]},
    )
    cache = BaseTokenCache(max_history=120)

    with caplog.at_level("WARNING"):
        cache.load_from_file(path, now=base)

    assert "overview_volume" in caplog.text
    assert "is not a list" in caplog.text
    assert "Base token cache" in caplog.text
    # The healthy sibling series is unaffected.
    assert cache.get_eth_price_history() == [(base - 10, 1.0)]
    assert cache.get_volume_history() == []
    # One line, not one per point.
    assert caplog.text.count("is not a list") == 1
